#!/bin/bash

set -e

tmpImg=`mktemp`
tmpConf=`mktemp`

trap cleanup 0 SIGTERM SIGKILL

_testEq() {
  if [ "$1" $2 "$3" ]; then
    echo -en "\e[32m[PASS]"
  else
    echo -en "\e[31m[FAIL]"
    echo -e "\e[0m $@"
    exit 1
  fi
  echo -e "\e[0m $@"
}

cleanup() {
  echo "Cleaning"
  rm -rf $tmpImg $tmpConf device.img
}

talkPermitTest() {
  local analogHex=./tests/bt6x2/talkPermit/analog.hex
  local offHex=./tests/bt6x2/talkPermit/off.hex
  local analogImg=./tests/bt6x2/talkPermit/analog.img
  local offImg=./tests/bt6x2/talkPermit/off.img
  local size=16

  local baseAddress=`diff $analogHex $offHex |  egrep ">" | sed -r "s/> //g;s/:.*//g"`
  xxd -r $analogHex > $analogImg
  xxd -r $offHex > $offImg

  diff  <(xxd -s 0x$baseAddress -l $size -c 1 $offImg) <(xxd -s 0x$baseAddress -l $size -c 1 $analogImg) | egrep ">"
  local byteAddress=`diff  <(xxd -s 0x$baseAddress -l 256 -c 1 $offImg) <(xxd -s 0x$baseAddress -l 256 -c 1 $analogImg) | egrep ">" | sed -r "s/> //g;s/:.*//g"`
  echo "Target byte address: $byteAddress"

  local offConf=./tests/bt6x2/talkPermit/off.conf
  local paramName="Talk Alert"

  ./dmrconfig $offImg > $offConf
  sed -r -i "s/^$paramName:.*/$paramName: 00/g" $offConf
  ./dmrconfig -c $offImg $offConf

  local after="`xxd -s 0x$byteAddress -l 1 -c 1 device.img | awk '{print $2}'`"
  _testEq "00" == "$after" "$paramName"

  sed -r -i "s/^$paramName:.*/$paramName: 01/g" $offConf
  egrep -i "^$paramName" $offConf
  ./dmrconfig -c $offImg $offConf
  after="`xxd -s 0x$byteAddress -l 1 -c 1 device.img | awk '{print $2}'`"
  _testEq "01" == "$after" "$paramName"
}

touchTest() {
  xxd -r ./tests/bt6x2/talkPermit/analog.hex > $tmpImg
  ./dmrconfig $tmpImg > $tmpConf
  vi $tmpConf
  ./dmrconfig -c $tmpImg $tmpConf
  if  cmp $tmpImg device.img; then
    echo -en "\e[32mPASS"
  else
    echo -en "\e[31mFAIL"
    vim -d ./tests/bt6x2/talkPermit/analog.hex <(xxd device.img) 
    exit 1
  fi
  echo -e "\e[0m ${FUNCNAME[0]}"
}

main() {
  # TODO touchTest has been failing
#  touchTest
  talkPermitTest
}

main $@
